### PR TITLE
Fix indexable deletion in EntityListener

### LINKED ISSUE #68: [Bug]: RemoveEntity message dispatching failed
### Plugin version

dev-master

### Sylius version

1.12

### What happened?

When we delete an entity, the `RemoveEntity` message dispatching failed.

As the message is dispatched on the `PostRemove` Doctrine event, the entity id is not set anymore.

I think we have two solutions:
- move the message dispatching on Doctrine `preRemove` event
- refactor the `EntityListener` to map the entity hash with the associated id, and keep the `RemoveEntity` message dispatching on `postRemove`

Any preference?

### Relevant log output

```shell
Symfony\Component\Messenger\Exception\HandlerFailedException:
Handling "Setono\SyliusMeilisearchPlugin\Message\Command\RemoveEntity" failed: The identifier id is missing for a query of Setono\SyliusMeilisearchPlugin\Tests\Application\Entity\Product

  at /sylius/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124
  at Symfony\Component\Messenger\Middleware\HandleMessageMiddleware->handle(object(Envelope), object(TraceableStack))
     (/sylius/app/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php:71)
  at Symfony\Component\Messenger\Middleware\SendMessageMiddleware->handle(object(Envelope), object(TraceableStack))
     (/sylius/app/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php:34)
  at Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware->handle(object(Envelope), object(TraceableStack))
```

### PR DESCRIPTION
**Pull request by SebLours**
Fix #68

### CODE REVIEW

File: src/EventListener/Doctrine/EntityListener.php [hunk 1]
```diff
@@ -8,13 +8,16 @@
...
 use Sylius\Component\Resource\Model\TranslationInterface;
 use Symfony\Component\Messenger\MessageBusInterface;
 
 final class EntityListener
 {
-    public function __construct(private readonly MessageBusInterface $commandBus)
-    {
+    public function __construct(
+        private readonly MessageBusInterface $commandBus,
+        private readonly SplObjectStorage $removeIndexableStorage = new SplObjectStorage(),
```
Comment (loevgaard) [inline src/EventListener/Doctrine/EntityListener.php:19]: It should not be a constructor argument

File: src/EventListener/Doctrine/EntityListener.php [hunk 2]
```diff
@@ -27,26 +30,47 @@ public function postUpdate(LifecycleEventArgs $eventArgs): void
...
     private function dispatch(LifecycleEventArgs $eventArgs, callable $message): void
+    {
+        $indexable = $this->extractIndexableFromEvent($eventArgs);
+
+        if ($indexable instanceof IndexableInterface) {
+            $this->commandBus->dispatch($message($indexable));
+        }
+    }
+
+    private function extractIndexableFromEvent(LifecycleEventArgs $eventArgs): ?IndexableInterface
```
Comment (loevgaard) [inline src/EventListener/Doctrine/EntityListener.php:62]: Should be static

File: src/EventListener/Doctrine/EntityListener.php [hunk 3]
```diff
@@ -27,26 +30,47 @@ public function postUpdate(LifecycleEventArgs $eventArgs): void
...
     }
 
     /**
      * @param callable(IndexableInterface):object $message
      */
     private function dispatch(LifecycleEventArgs $eventArgs, callable $message): void
+    {
+        $indexable = $this->extractIndexableFromEvent($eventArgs);
+
+        if ($indexable instanceof IndexableInterface) {
```
Comment (loevgaard) [inline src/EventListener/Doctrine/EntityListener.php:57]: It's a style issue I guess, but I like doing

```php
if (null === $indexable) {
    return;
}
```

instead

File: src/EventListener/Doctrine/EntityListener.php [hunk 4]
```diff
@@ -27,26 +30,47 @@ public function postUpdate(LifecycleEventArgs $eventArgs): void
...
+            $this->removeIndexableStorage->attach($indexable, $indexable->getId());
+        }
+    }
+
     public function postRemove(LifecycleEventArgs $eventArgs): void
     {
-        $this->dispatch($eventArgs, static fn (IndexableInterface $entity) => RemoveEntity::new($entity));
+        $this->dispatch(
+            $eventArgs,
+            fn (IndexableInterface $entity) => new RemoveEntity($entity::class, $this->removeIndexableStorage[$entity]),
```
Comment (loevgaard) [inline src/EventListener/Doctrine/EntityListener.php:46]: I guess we need to check if this `$this->removeIndexableStorage[$entity]` exists first?

**Review by loevgaard — APPROVED** [review]
Great work, once again @SebLours 🥇
